### ISSUE TITLE
Using f2lp in cplus2asp system

### ISSUE THREAD

**Issue by yigong837** [azreasoners/F2LP#1]
I have compiled and installed cplus2asp system through git clone on Ubuntu, but it does not contain f2lp. My problem is how to compile and install f2lp when using f2lp as a part of cplus2asp.

**Comment by azreasoners** [comment]
You can follow the steps in the [Cplus2ASP GitHub page](https://github.com/azreasoners/Cplus2ASP) where the following step installs f2lp into your "/usr/local/bin/".
```bash
gcc externals/f2lp/f2lp.c -o f2lp
sudo cp f2lp /usr/local/bin/
```
I just tested the steps in the Cplus2ASP GitHub page on _Ubuntu 18.04.3 LTS (GNU/Linux 5.4.0-53-generic x86_64)_ and it works without an issue. 
If this does not resolve your problem, please provide me with more information to replicate your situation. Thanks.

**Comment by yigong837** [comment]
I solved the problem according to the above steps, thank you.
